name: mclarence.xyz
description: 	(￣▽￣)ノ
meta_description: "mclarence.xyz"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://mclarence.xyz"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Clarence"

# Disqus config
disqus-shortname: ""
